services:
  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411:9411'
  my-prometheus:
    image: prom/prometheus
    container_name: my-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ## Tempo
    my-tempo:
      image: grafana/tempo
      container_name: my-tempo
      command: [ "-config.file=/etc/tempo.yaml" ]
      volumes:
        - ./docker/tempo/tempo.yml:/etc/tempo.yaml:ro
        - ./docker/tempo/tempo-data:/tmp/tempo
      ports:
        - "3200:3200" # Tempo
        - "9411:9411" # zipkin
