spring:
  application:
              name=observability-spring-grafana
  datasource:
    url=jdbc:h2:mem:products-db
  docker:
    compose:
      enabled=false:
server:
     port: 8087

management:
  endpoints:
        web:
         exposure:
               include=*

